### ISSUE TITLE
"attempted  duplicate class definition for name ..." issue

### ISSUE THREAD

**Issue by eschava** [toddlipcon/jcarder#4]
in branch lockclasses-new
It happens when ClassWriter.getCommonSuperClass method loads reference to class that is going to be processed by class transformer. Workaround - store hierarchy of classes to be able to find common super class without loading class instance

**Comment by eschava** [comment]
This issue is not reproduced when ClassWriter.COMPUTE_FRAMES flag is omitted

**Comment by eschava** [comment]
I've found two solutions for this issue in 3rd-party libraries

1. Simple one:
https://svn.apache.org/repos/asf/aries/tags/org.apache.aries.proxy.impl-0.4/src/main/java/org/apache/aries/proxy/impl/common/OSGiFriendlyClassWriter.java

2. More advanced one (I've checked it with JCarder and it definitely works):
https://github.com/Devexperts/jagent/tree/master/jagent-impl/src/main/java/com/devexperts/jagent
(use ClassInfo* classes + FrameClassWriter)

**Comment by toddlipcon** [comment]
I just saw this issue. I think I may have fixed this same issue by upgrading to asm 6 earlier this year: https://github.com/toddlipcon/jcarder/commit/2b2fbe20902a43aa19ed1b6a4f924c818f7596f9

Can you take a look on the 'cloudera' branch?

**Comment by eschava** [comment]
Right, it looks fixed using the way similar to OSGiFriendlyClassWriter
